version: '3.8'

services:
  # 1. DATABASE
  db-postgres:
    image: postgres:17-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user_ganteng
      POSTGRES_PASSWORD: SueWWKeTsg
      POSTGRES_DB: debt
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. BACKEND NESTJS
  my-backend:
    build: .
    container_name: nestjs-app
    restart: always
    depends_on:
      - db-postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://user_ganteng:SueWWKeTsg@db-postgres:5432/debt
      JWT_SECRET: "e7d9fa1eb45a504370c3714fd7dbb3432ef9c89f00409a59b20d193c20a938c3db325ef21ef4076eadda5668bcd9bb154c17b2b8c18fa5b218ccf23480ef6e2f"

    # Perintah: Migrate database dulu baru nyalain aplikasi
    command: sh -c "npx prisma migrate deploy && node dist/main"

  # 3. PORTAINER (Si Visual Dashboard)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-gui
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  pgdata:
  portainer_data: