version: '3.8'

services:
  # 1. DATABASE
  db-postgres:
    image: postgres:17-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user_ganteng
      POSTGRES_PASSWORD: SueWWKeTsg
      POSTGRES_DB: debt
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # 2. BACKEND NESTJS
  my-backend:
    build: .
    container_name: nestjs-app
    restart: always
    depends_on:
      - db-postgres
    ports:
      - "3000:3000"
    environment:
      # Koneksi ke DB pakai nama service: db-postgres
      DATABASE_URL: postgresql://user_ganteng:SueWWKeTsg@db-postgres:5432/debt
    # Perintah: Migrate database dulu baru nyalain aplikasi
    command: sh -c "npx prisma migrate deploy && node dist/main"

  # 3. PORTAINER (Si Visual Dashboard)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-gui
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  pgdata:
  portainer_data: